module semantic.analyzer;
import parser.all_nodes;
import semantic.info;
import parser.j_parser;
import semantic.environment;

/**
* This class performs semantic analysis on an AST
* generated by a Parser.
*/
class SemanticAnalyzer
{
	///The AST
	Node ast;

	/**
	* Constructs the semantic analyzer with the file to parse.
	*/
	this(Node ast)
	{
		this.ast = ast;
	}
}